name: Deploy to Play Store "Internal"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Decode google-services JSON File
        uses: timheuer/base64-to-file@v1.2
        id: google_services_json_file
        with:
          fileName: 'google-services.json'
          fileDir: './app/'
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      #      - name: Run tests
      #        run: bundle exec fastlane android test

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1.2
        id: service_account_json_file
        with:
          fileName: 'service_account.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1.2
        id: android_keystore
        with:
          fileName: 'android_keystore.keystore'
          encodedString: ${{ secrets.RELEASE_KEYSTORE_FILE }}

      - name: Build & deploy Android release
        run: bundle exec fastlane android deploy
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ steps.service_account_json_file.outputs.filePath }}